# Generated by Django 4.2.23 on 2025-06-23 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='cultura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=50)),
                ('Tempo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='propriedades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=50)),
                ('Localizacao', models.CharField(max_length=100)),
                ('Tamanho', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name_plural': 'Propriedades',
            },
        ),
        migrations.CreateModel(
            name='TipoInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Tipos de Insumo',
            },
        ),
        migrations.CreateModel(
            name='insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=45)),
                ('Descricao', models.CharField(max_length=45)),
                ('Tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='propriedade_rural.tipoinsumo')),
            ],
        ),
        migrations.CreateModel(
            name='funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data_admissao', models.DateField()),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='propriedade_rural.cargo')),
                ('propriedade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='propriedade_rural.propriedades')),
            ],
        ),
    ]
