# Generated by Django 4.2.23 on 2025-06-26 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('propriedade_rural', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funcionario',
            old_name='data_admissao',
            new_name='dataAdmissao',
        ),
        migrations.CreateModel(
            name='plantio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('areaPlantada', models.CharField(max_length=100000)),
                ('data', models.DateField()),
                ('cult', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='propriedade_rural.cultura')),
                ('prop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='propriedade_rural.propriedades')),
            ],
        ),
    ]
